# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField(verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'Donnée',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.TextField(verbose_name='mot de passe')),
                ('encrypted_private_key', models.TextField(verbose_name='clef privé')),
                ('public_key', models.TextField(verbose_name='clef publique')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'Clef',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Key', verbose_name='clef'),
        ),
        migrations.AddField(
            model_name='data',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
    ]
