# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='comment',
            field=models.TextField(default='', null=True, verbose_name='commentaires'),
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='nom'),
        ),
    ]
