# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20161231_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='commentaires'),
        ),
    ]
